version: 2
jobs:
  lint:
      docker:
        - image: koalaman/shellcheck-alpine:stable
      steps:
        - checkout
        - run:
            name: Shellcheck
            command: |
              shellcheck -s bash src/*

  coverage:
      docker:
        - image: circleci/ruby:latest
      steps:
        - checkout
        - run:
            name: Install
            command: |
              gem install bashcov
        - run:
            name: Coverage
            command: |
              bashcov --skip-uncovered ./test.sh

  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install
          command: |
            git clone https://github.com/sstephenson/bats.git 
            cd bats
            ./install.sh /home/circleci/project
      - run:
          name: Test
          command: '/home/circleci/project/bin/bats /home/circleci/project/test/'

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test:
          requires:
            - lint
          filters:
            branches:
              only: master
      - coverage