version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install
          command: 'git clone https://github.com/sstephenson/bats.git && cd bats && ./install.sh $CIRCLE_WORKING_DIRECTORY'
      - run:
          name: Test
          command: 'ls $CIRCLE_WORKING_DIRECTORY'
          # command: '$CIRCLE_WORKING_DIRECTORY/bin/bats $CIRCLE_PROJECT_REPONAME/test/'
      # - run:
      #     name: Lint
      #     command: 'shellcheck -s bash src/*'
      #   run:
      #     name: Coverage
      #     command: 'bashcov --skip-uncovered ./test.sh'
