version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install
          command: |
            git clone https://github.com/sstephenson/bats.git 
            cd bats
            ./install.sh /home/circleci/project
      - run:
          name: Test
          command: '/home/circleci/project/bin/bats /home/circleci/project/test/'
      # - run:
      #     name: Lint
      #     command: 'shellcheck -s bash src/*'
      #   run:
      #     name: Coverage
      #     command: 'bashcov --skip-uncovered ./test.sh'
