version: 2
jobs:
  shellcheck:
      docker:
        - image: koalaman/shellcheck-alpine:stable
      steps:
        - checkout
        - run:
            name: Check Scripts
            command: |
              find . -type f -name '*.sh' | xargs shellcheck --external-sources

  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install
          command: |
            git clone https://github.com/sstephenson/bats.git 
            cd bats
            ./install.sh /home/circleci/project
      - run:
          name: Test
          command: '/home/circleci/project/bin/bats /home/circleci/project/test/'

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - test:
          requires:
            - shellcheck
          filters:
            branches:
              only: master